### ISSUE TITLE
ndk-build-arm

### ISSUE THREAD

**Issue by atsushieno** [atsushieno/android-fluidsynth#1]
It is desirable to build it with ndk-build without binary hack for arm, but so far it fails to build with ndk-build:

<pre>
[armeabi-v7a] Compile thumb  : fluidsynth <= fluid_gen.c
In file included from /home/atsushi/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed/syslimits.h:7:0,
                 from /home/atsushi/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed/limits.h:34,
                 from build/dist/android_armv7/lib/glib-2.0/include/glibconfig.h:11,
                 from build/dist/android_armv7/include/glib-2.0/glib/gtypes.h:32,
                 from build/dist/android_armv7/include/glib-2.0/glib/galloca.h:32,
                 from build/dist/android_armv7/include/glib-2.0/glib.h:30,
                 from build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/utils/fluidsynth_priv.h:25,
                 from jni/../build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/synth/fluid_gen.h:25,
                 from jni/../build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/synth/fluid_gen.c:22:
/home/atsushi/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9/include-fixed/limits.h:168:61: error: no include path in which to search for limits.h
 #include_next &lt;limits.h>  /* recurse down to the real one */
                                                             ^
In file included from build/dist/android_armv7/include/glib-2.0/glib/galloca.h:32:0,
                 from build/dist/android_armv7/include/glib-2.0/glib.h:30,
                 from build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/utils/fluidsynth_priv.h:25,
                 from jni/../build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/synth/fluid_gen.h:25,
                 from jni/../build/sources/android_armv7/fluidsynth-1.1.6/fluidsynth/src/synth/fluid_gen.c:22:
build/dist/android_armv7/include/glib-2.0/glib/gtypes.h:35:18: fatal error: time.h: No such file or directory
 #include &lt;time.h>
                  ^
compilation terminated.

</pre>

And I have no idea how to fix it.

**Comment by atsushieno** [comment]
Still problematic with NDK r11...

**Comment by billkirim** [comment]
Try this one.

Add on your Makefile
```
ndk-build-arm:
       $(ANDROID_NDK)/ndk-build CUSTOM_ARCH=armv7 APP_ABI=armeabi-v7a
ndk-build-x86:
	$(ANDROID_NDK)/ndk-build CUSTOM_ARCH=x86 APP_ABI=x86
```

And on your Android.mk
`TARGET_ARCH_DIR = android_$(CUSTOM_ARCH)`

**Comment by atsushieno** [comment]
Awesome! That worked. Thanks a lot :-) (6c87c73)
