### ISSUE TITLE
JNI implementation

### ISSUE THREAD

**Issue by Egorkansk** [atsushieno/android-fluidsynth#10]
Hi! I have idea of creating application of automatic guitar chords synth, i was tryed AudioTrack API but it have a lag, how i can use your library with JNI interface in android studio or Eclipse, can you help me to understand please

**Comment by atsushieno** [comment]
This is an old repo that I'm not going to track issues. Have a look at https://github.com/atsushieno/fluidsynth-midi-service-j and if you still have questions then shoot there. (But I'm not going to explain how to begin basic JNI development on AS - that's what I have never tried.)
