### ISSUE TITLE
"make prepare" is not work. 

### ISSUE THREAD

**Issue by juuk100** [atsushieno/android-fluidsynth#4]
I have a problem with the build you provided.

Running $ make prepare will cause the following problem.

cd external / cerbero && CERBERO_LOCAL_CONFIG = .. / .. / custom.cbc ./cerbero-uninstalled -c config / cross-android-armv7.cbc bootstrap
/ bin / sh: ./cerbero-uninstalled: No such file or directory
make: *** [prepare] Error 127

Perhaps "cerbero" is not connected or it can not be found in git.

**Comment by atsushieno** [comment]
Just fixed it. Thanks.
