### ISSUE TITLE
"make prepare" fails

### ISSUE THREAD

**Issue by sonicdebris** [atsushieno/android-fluidsynth#6]
After recursively cloning, I launch `make prepare` and I get this:
```
cd external/cerbero && CERBERO_LOCAL_CONFIG=../../custom.cbc ./cerbero-uninstalled -c config/cross-android-armv7.cbc bootstrap
Traceback (most recent call last):
  File "./cerbero-uninstalled", line 8, in <module>
    from cerbero.main import main
  File "./cerbero/main.py", line 19, in <module>
    from cerbero import hacks
  File "./cerbero/hacks.py", line 132, in <module>
    from cerbero.utils.shell import call as shell_call
  File "./cerbero/utils/shell.py", line 42, in <module>
    PLATFORM = system_info()[0]
  File "./cerbero/utils/__init__.py", line 206, in system_info
    raise FatalError("Distribution '%s' not supported" % str(d))
cerbero.errors.FatalError
Makefile:12: recipe for target 'prepare' failed
make: *** [prepare] Error 1
```
I am on Ubuntu 17.10 64 bit

**Comment by atsushieno** [comment]
This project uses cerbero as the builder which resolves almost everything fluidsynth needs for Android NDK-based builds without ndk-build. Ubuntu 11.10 is not supported on cerbero yet because that version is too new. Wait for upstream fix?

**Comment by sonicdebris** [comment]
Thanks, I will try with some other distro. Which one are you using?

**Comment by atsushieno** [comment]
I'm on Ubuntu 17.04. But before switching to other distros you might want to try making changes in cerbero, I assume it is one-liner-ish fix.
